config/routes.rb
Rails.application.routes.draw do
  %w[404 422 500].each do |code|
    get code, to: 'errors#show', code:, as: "error_#{code}"
  end

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  root to: 'site#index'

  get 'documents/images',
      to: 'documents#images',
      as: 'document_images'

  post 'documents/(:id)/mark',
       to: 'documents#mark',
       as: 'document_mark'

  post 'documents/(:id)/status',
       to: 'documents#status',
       as: 'document_status'

  get 'autenticidade/documentos',
      to: 'documents#document',
      as: 'document'

  get 'autenticidade/documentos/(:code)',
      to: 'documents#show',
      as: 'confirm_document_code'

  post 'autenticidade/documentos/(:code)',
       to: 'documents#confirm_document',
       as: 'confirm_document'

  post 'documents/(:id)/code', to: 'documents#code', as: 'document_code'
  post 'documents/(:id)/data', to: 'documents#data', as: 'document_data'
  post 'documents/(:id)/request', to: 'documents#request_data', as: 'document_request'

  post '/sidebar', to: 'site#sidebar', as: 'site_sidebar'

  #========================================
  # Responsible
  #========================================
  authenticate :professor do
    namespace :responsible do
      root to: 'dashboard#index'

      resources :academics,
                constraints: { id: /[0-9]+/ },
                concerns: :paginatable

      resources :professors,
                constraints: { id: /[0-9]+/ },
                concerns: :paginatable

      resources :orientations,
                constraints: { id: /[0-9]+/ },
                concerns: :paginatable

      resources :external_members,
                constraints: { id: /[0-9]+/ },
                concerns: :paginatable

      resources :institutions,
                constraints: { id: /[0-9]+/ },
                concerns: :paginatable

      resources :base_activities,
                except: :index,
                constraints: { id: /[0-9]+/ }

      resources :calendars,
                except: :index,
                constraints: { id: /[0-9]+/ },
                concerns: :paginatable do
                  resources :activities
                end

      resources :examination_boards,
                except: [:new, :create],
                constraints: { id: /[0-9]+/ },
                concerns: :paginatable

      resources :site,
                only: [:edit, :update],
                constraints: { id: /[0-9]+/ }

      resources :pages,
                constraints: { id: /[0-9]+/ },
                concerns: :paginatable

      resources :images,
                except: :show,
                constraints: { id: /[0-9]+/ },
                concerns: :paginatable

      resources :attached_documents,
                except: :show,
                constraints: { id: /[0-9]+/ },
                concerns: :paginatable

      get 'examination_boards/tcc_one',
          to: 'examination_boards#tcc_one',
          as: 'examination_boards_tcc_one'

      get 'examination_boards/tcc_one/current_semester',
          to: 'examination_boards#tcc_one_current_semester',
          as: 'examination_boards_tcc_one_current_semester'

      get 'examination_boards/tcc_one/new',
          to: 'examination_boards#new_to_tcc_one',
          as: 'examination_boards_new_tcc_one'

      post 'examination_boards/tcc_one',
           to: 'examination_boards#create_to_tcc_one',
           as: 'examination_boards_create_tcc_one'

      get 'examination_boards/tcc_two',
          to: 'examination_boards#tcc_two',
          as: 'examination_boards_tcc_two'

      get 'examination_boards/tcc_two/current_semester',
          to: 'examination_boards#tcc_two_current_semester',
          as: 'examination_boards_tcc_two_current_semester'

      get 'examination_boards/tcc_two/new',
          to: 'examination_boards#new_to_tcc_two',
          as: 'examination_boards_new_tcc_two'

      post 'examination_boards/tcc_two',
           to: 'examination_boards#create_to_tcc_two',
           as: 'examination_boards_create_tcc_two'

      post 'calendars/activities/by-calendar',
           to: 'activities#index_by_calendar',
           as: 'calendar_activities_by_calendar'

      get 'calendars/tcc_one', to: 'calendars#tcc_one', as: 'calendars_tcc_one'
      get 'calendars/tcc_two', to: 'calendars#tcc_two', as: 'calendars_tcc_two'

      get 'base_activities/tcc_one', to: 'base_activities#tcc_one', as: 'base_activities_tcc_one'
      get 'base_activities/tcc_two', to: 'base_activities#tcc_two', as: 'base_activities_tcc_two'

      get 'orientations/tcc_one', to: 'orientations#tcc_one', as: 'orientations_tcc_one'
      get 'orientations/tcc_two', to: 'orientations#tcc_two', as: 'orientations_tcc_two'

      get 'professors/(:id)/orientations/tcc_one',
          to: 'professors#tcc_one',
          as: 'professor_orientations_tcc_one'

      get 'professors/(:id)/orientations/tcc_two',
          to: 'professors#tcc_two',
          as: 'professor_orientations_tcc_two'

      put 'documents/(:id)/judgment', to: 'documents#judgment', as: 'document_judgment'

      get 'reports', to: 'dashboard#report', as: 'reports'

      get 'site/pages/order', to: 'pages#order', as: 'pages_order'
      put 'site/sidebar/update', to: 'pages#update_order', as: 'update_sidebar'

      get 'professors/available',
          to: 'professors#available',
          as: 'professors_available'

      get 'professors/unavailable',
          to: 'professors#unavailable',
          as: 'professors_unavailable'

      get 'orientations/current_tcc_one',
          to: 'orientations#current_tcc_one',
          as: 'orientations_current_tcc_one'

      get 'orientations/current_tcc_two',
          to: 'orientations#current_tcc_two',
          as: 'orientations_current_tcc_two'

      get 'orientations/migration/(page/:page)',
          to: 'orientations_migration#index',
          as: 'orientations_migration'

      post 'orientations/(:id)/migrate',
           to: 'orientations_migration#migrate',
           as: 'orientations_migrate'

      post 'orientations/(:id)/renew', to: 'orientations#renew', as: 'orientations_renew'
      post 'orientations/(:id)/cancel', to: 'orientations#cancel', as: 'orientations_cancel'

      get 'orientations/(:id)/documents',
          to: 'orientations#documents',
          as: 'orientation_documents'

      get 'orientations/(:id)/documents/(:document_id)',
          to: 'orientations#document',
          as: 'orientation_document'

      get 'orientations/(:orientation_id)/calendars/(:calendar_id)/activities',
          to: 'orientation_activities#index',
          as: 'orientation_calendar_activities'

      # get 'orientations/(:id)/activities/(:activity_id)',
      get 'orientations/(:orientation_id)/calendars/(:calendar_id)/activities/(:id)',
          to: 'orientation_activities#show',
          as: 'orientation_calendar_activity'

      get 'academics/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'academics#index',
          as: 'academics_search'

      get 'professors/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'professors#index',
          as: 'professors_search'

      get 'professors/available/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'professors#available',
          as: 'professors_available_search'

      get 'professors/unavailable/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'professors#unavailable',
          as: 'professors_unavailable_search'

      get 'external_members/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'external_members#index',
          as: 'external_members_search'

      get 'institutions/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'institutions#index',
          as: 'institutions_search'

      get 'examination_boards/tcc_one/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'examination_boards#tcc_one',
          as: 'examination_boards_tcc_one_search'

      get 'examination_boards/tcc_one/current_semester/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'examination_boards#tcc_one_current_semester',
          as: 'examination_boards_tcc_one_current_semester_search'

      get 'examination_boards/tcc_two/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'examination_boards#tcc_two',
          as: 'examination_boards_tcc_two_search'

      get 'examination_boards/tcc_two/current_semester/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'examination_boards#tcc_two_current_semester',
          as: 'examination_boards_tcc_two_current_semester_search'

      get 'orientations/current_tcc_one/(:status)/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'orientations#current_tcc_one',
          as: 'orientations_search_current_tcc_one'

      get 'orientations/current_tcc_two/(:status)/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'orientations#current_tcc_two',
          as: 'orientations_search_current_tcc_two'

      get 'orientations/tcc_one/(:status)/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'orientations#tcc_one',
          as: 'orientations_search_tcc_one'

      get 'orientations/tcc_two/(:status)/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'orientations#tcc_two',
          as: 'orientations_search_tcc_two'

      get 'base_activities/tcc_one/search/(:term)/(page/:page)',
          constraints: { term: %r{[^/]+} },
          to: 'base_activities#tcc_one',

app/controllers/academics/documents_controller.rb
class Academics::DocumentsController < Academics::BaseController
  include DocumentSignature
  before_action :set_document, only: [:show, :sign]
  before_action :can_view, only: :show
  before_action :set_signature, only: [:show, :sign]

  add_breadcrumb I18n.t('breadcrumbs.documents.pending'),
                 :academics_documents_pending_path,
                 only: :pending

  add_breadcrumb I18n.t('breadcrumbs.documents.signed'),
                 :academics_documents_signed_path,
                 only: :signed

  def pending
    @documents = current_academic.documents_pending(params[:page])
  end

  def signed
    @documents = current_academic.documents_signed(params[:page])
  end

  def show
    add_breadcrumb I18n.t('breadcrumbs.documents.show'), academics_document_path(@document)
  end

  def sign
    confirm_and_sign(current_academic, current_academic.ra)
  end

  private

  def set_document
    @document = current_academic.documents.find_by(id: params[:id])
  end

  def set_signature
    @signature = @document.signature_by_user(current_academic.id, :academic)
  end

  def can_view
    return if @document.present?

    flash[:alert] = I18n.t('flash.not_authorized')
    redirect_to academics_documents_pending_path
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:data, :mark, :code, :status, :request_data]
  before_action :set_document_by_code, only: [:show, :confirm_document]
  before_action :can_show, only: :show
  include JsonMessage

  def mark
    render json: @document.mark
  end

  def code
    render json: {
      all_signed: @document.all_signed?, code: @document.code, link: confirm_document_code_url
    }
  end

  def status
    render json: @document.status_table
  end

  def document; end

  def show
    @signature = @document.signatures.first
    success_document_authenticated_message
    @signatures = @document.mark
  end

  def data
    render json: @document.content
  end

  def request_data
    render json: @document.request
  end

  def confirm_document
    if @document&.all_signed?
      flash[:success] = I18n.t('json.messages.documents.success.authenticated')
      redirect_to confirm_document_code_path(@document.code)
    else
      flash[:error] = document_not_found_message
    end
  end

  def images
    helpers = ActionController::Base.helpers
    render json: { sgtcc_seal: helpers.asset_url('sgtcc_signature.png'),
                   utfpr_logo: helpers.asset_url('utfpr_logo.png') }
  end

  private

  def set_document_by_code
    @document = Document.find_by(code: params[:code])
  end

  def set_document
    @document = Document.find(params[:id])
  end

  def can_show
    return if @document.present? && @document&.all_signed?

    error_document_not_found_message
    redirect_to document_path
  end
end

app/controllers/external_members/documents_controller.rb
class ExternalMembers::DocumentsController < ExternalMembers::BaseController
  include DocumentSignature
  before_action :set_document, only: [:show, :sign]
  before_action :can_view, only: :show
  before_action :set_signature, only: [:show, :sign]

  add_breadcrumb I18n.t('breadcrumbs.documents.pending'),
                 :external_members_documents_pending_path,
                 only: :pending

  add_breadcrumb I18n.t('breadcrumbs.documents.signed'),
                 :external_members_documents_signed_path,
                 only: :signed

  def pending
    @documents = current_external_member.documents_pending(params[:page])
  end

  def signed
    @documents = current_external_member.documents_signed(params[:page])
  end

  def show
    add_breadcrumb I18n.t('breadcrumbs.documents.show'),
                   external_members_document_path(@document)
  end

  def sign
    confirm_and_sign(current_external_member, current_external_member.email)
  end

  private

  def set_document
    id = params[:id]
    @document = current_external_member.documents.find_by(id:)
    @document = current_external_member.all_documents.find_by(id:) if @document.blank?
  end

  def set_signature
    @signature = @document.signature_by_user(current_external_member.id,
                                             current_external_member.user_types)
  end

  def can_view
    return if @document.present?

    flash[:alert] = I18n.t('flash.not_authorized')
    redirect_to external_members_documents_pending_path
  end
end

app/controllers/professors/documents_controller.rb
class Professors::DocumentsController < Professors::BaseController
  include DocumentSignature
  before_action :set_document, only: [:show, :sign]
  before_action :set_document_for_responsible, only: :show
  before_action :set_show_sign, only: :show
  before_action :can_view, only: :show
  before_action :set_signature, only: [:show, :sign]

  add_breadcrumb I18n.t('breadcrumbs.documents.reviewing'),
                 :professors_documents_reviewing_path,
                 only: :reviewing

  add_breadcrumb I18n.t('breadcrumbs.documents.pending'),
                 :professors_documents_pending_path,
                 only: :pending

  add_breadcrumb I18n.t('breadcrumbs.documents.signed'),
                 :professors_documents_signed_path,
                 only: :signed

  def pending
    @documents = current_professor.documents_pending(params[:page])
  end

  def signed
    @documents = current_professor.documents_signed(params[:page])
  end

  def reviewing
    @documents = current_professor.documents_reviewing(params[:page])
  end

  def show
    add_breadcrumb I18n.t('breadcrumbs.documents.show'),
                   professors_document_path(@document)
  end

  def sign
    confirm_and_sign(current_professor, current_professor.username)
  end

  private

  def set_document
    id = params[:id]
    @document = current_professor.documents.find_by(id:)
    @document = current_professor.all_documents.find_by(id:) if @document.blank?
  end

  def set_document_for_responsible
    for_responsible = current_professor.responsible? && @document.blank?
    @document = Document.find(params[:id]) if for_responsible
    @not_show_sign_button = true if for_responsible
  end

  def set_show_sign
    return if @document.blank? || @document&.content&.blank?

    examination_board_json = @document.content['examination_board']
    return if examination_board_json.blank?

    examination_board = ExaminationBoard.find(examination_board_json['id'])
    @not_show_sign_button = true unless examination_board.available_defense_minutes?
  end

  def set_signature
    @signature = @document.signature_by_user(current_professor.id, current_professor.user_types)
  end

  def can_view
    return if @document.present?

    flash[:alert] = I18n.t('flash.not_authorized')
    redirect_to professors_documents_pending_path
  end
end

app/controllers/responsible/documents_controller.rb
class Responsible::DocumentsController < Responsible::BaseController
  before_action :set_document, only: :judgment

  add_breadcrumb I18n.t('breadcrumbs.orientations.index'),
                 :responsible_orientations_tcc_one_path,
                 only: :orientation

  def judgment
    if @document.professor_signed?(current_professor)
      render json: { status: false,
                     message: I18n.t('json.messages.documents.errors.update') }
    else
      render json: { status: @document.save_judgment(current_professor, params),
                     message: I18n.t('json.messages.documents.success.update') }
    end
  end

  private

  def set_document
    @document = Document.find(params[:id])
  end
end

app/views/shared/documents/_base_term_layout.html.erb
<div class="card">
  <div id="term" class="card-body signature-document w-80">
    <header>
      <%= render "shared/documents/term_header", document: document %>
    </header>

    <main>
        <div class="d-block w-80" style="margin-top: 50px; margin-bottom: 50px;">
          <h4 class="text-center">
            <%= document.content.dig("title") %>
          </h4>
        </div>

      <%= yield %>
    </main>

    <footer>
      <%= render "shared/documents/term_footer", created_at: document.content.dig("document", "created_at") || "—" %>
      <div class="clearfix"></div>

      <%= render "shared/documents/signature_mark", document: document %>
    </footer>

    <% if document.content.dig("document", "obs").present? %>
      <p class="fs-6 mt-5">
        <strong>Observação: </strong> <%= document.content.dig("document", "obs") %>
      </p>
    <% end %>
  </div>
</div>

app/views/shared/documents/_component.html.erb
<%= render partial: "shared/documents/document_types/#{@document.document_type.identifier}" %>

app/views/shared/documents/_pending.html.erb
<% provide(:page_title, t('breadcrumbs.documents.pending')) %>
<% provide(:head_title, t('breadcrumbs.documents.pending')) %>

<%= render 'shared/documents/table' %>

<%= paginate @documents %>

app/views/shared/documents/_reviewing.html.erb
<% provide(:page_title, t('breadcrumbs.documents.reviewing')) %>
<% provide(:head_title, t('breadcrumbs.documents.reviewing')) %>

<div class="text-right mt-3">
  <%= page_entries_info @documents, entry_name: t('breadcrumbs.documents.reviewing').downcase  %>
</div>

<div class="table-striped mt-3 table-responsive w-100">
  <table class="table card-table table-vcenter text-nowrap">
    <thead>
      <tr>
        <th><%= Signature.human_attribute_name('orientation') %></th>
        <th><%= Signature.human_attribute_name('academic') %></th>
        <th><%= Signature.human_attribute_name('document_type') %></th>
        <th><%= Signature.human_attribute_name('status') %></th>
        <th><%= Signature.human_attribute_name('created_at') %></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <%= render('shared/no_results') if @documents.empty? %>
      </tr>
      <% @documents.each do |document| %>
        <%= render 'professors/documents/document_review', document: document %>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @documents %>

app/views/shared/documents/_show.html.erb
<% provide(:head_title, t('breadcrumbs.documents.show')) %>
<% provide(:page_title) do %>
  <signature-show-title />
<% end %>

<div class="clearfix mb-4">
  <div class="float-right ml-2">
    <signature-download-button
      head-title="<%= t('breadcrumbs.documents.show') %>"
      document-title="<%= @document.filename %>" />
  </div>

  <% unless @signature&.status || @not_show_sign_button %>
    <div>
      <signature-confirm
        label="<%= label %>"
        url="<%= confirm_url %>" />
    </div>

    <div class="float-right">
      <signature-button
        show-title="<%= t('breadcrumbs.signatures.TCO.show',
                           academic: @document.orientation.academic.name) %>" />
    </div>
  <% end %>
</div>

<div class="container">
  <div>
    <%= render 'shared/documents/component', document: @document %>
  </div>
  <div>
    <signature-status
      url="<%= document_status_path(@document) %>" />
  </div>
</div>

<div class="d-flex">
  <%= link_to t('simple_form.buttons.back'), back_url, class: 'btn btn-secondary' %>
</div>

app/views/shared/documents/_signature_code.html.erb
  <% base_url = "#{request.base_url}/autenticidade/documentos" %>
  <div class="signature-code">
    <hr class="m-0">
    <div class="py-4 d-flex">
      <div class="float-left mr-2">
        <%= image_tag(
          RQRCode::QRCode.new(
            base_url
          ).as_png(size: 100).to_data_url,
          class: 'mr-5',
          alt: "QR Code de verificação",
          style: "width: 100px; height: 100px; max-width: 200%;"
        ) %>
      </div>
      <p>
        A autenticidade deste documento pode ser conferida no site
        <u>
          <a
            href="<%= base_url %>"
            target="_blank"
            class="text-dark"
          >
            <%= base_url %>
          </a>
        </u>,
        informando o código verificador
        <b><%= document.code %></b>.
      </p>
    </div>
    <hr class="m-0">
  </div>

app/views/shared/documents/_signature_mark.html.erb
<div>
  <hr class="m-0">
  <% @signatures.each do |signature| %>
    <div class="signature_mark">
      <div class="py-4">
        <%= image_tag(
              asset_path("sgtcc_signature.png"),
              class: "float-left mr-2",
              style: "width: 100px;"
            ) %>

        <p>
          Documento assinado eletronicamente por
          <strong><%= signature[:name] %>, <%= signature[:role] %>,</strong>
          em <%= signature[:date] %>, às <%= signature[:time] %>,
          conforme horário oficial de Brasília, com fundamento no art. 6º, § 1º, do
          <u>
            <a href="http://www.planalto.gov.br/ccivil_03/_Ato2015-2018/2015/Decreto/D8539.htm"
               target="_blank" class="text-dark">
              Decreto nº 8.539, de 8 de outubro de 2015
            </a>
          </u>.
        </p>
      </div>
      <hr class="m-0">
      <div class="clearfix"></div>
    </div>
  <% end %>

  <div>
    <%= render "shared/documents/signature_code", document: @document %>
  </div>

</div>

app/views/shared/documents/_signed.html.erb
<% provide(:page_title, t('breadcrumbs.documents.signed')) %>
<% provide(:head_title, t('breadcrumbs.documents.signed')) %>

<%= render 'shared/documents/table' %>

<%= paginate @documents %>

app/views/shared/documents/_table.html.erb
<div class="text-right mt-3">
  <%= page_entries_info @documents %>
</div>

<div class="table-striped mt-3 table-responsive w-100">
  <table class="table card-table table-vcenter text-nowrap">
    <thead>
      <tr>
        <th><%= Document.human_attribute_name('orientation') %></th>
        <th><%= Document.human_attribute_name('academic') %></th>
        <th><%= Document.human_attribute_name('document_type') %></th>
        <th><%= Document.human_attribute_name('all_signed') %></th>
        <th><%= Document.human_attribute_name('created_at') %></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <%= render('shared/no_results') if @documents.empty? %>
      </tr>
      <%= render partial: "#{namespace}/documents/document", collection: @documents %>
    </tbody>
  </table>
</div>

app/views/shared/documents/_tbody.html.erb
<td>
   <span data-toggle="tooltip" title="<%= document.orientation.title %>">
      <%= link_to document.orientation.short_title, show_path %>
   </span>
</td>

<td><%= document.orientation.academic.name %></td>

<td>
   <span data-toggle="tooltip" title="<%= document.document_type.name %>">
      <%= document.document_type.identifier.upcase %>
   </span>
</td>

<td>
   <%= t("helpers.boolean.#{document.all_signed?}") %>
</td>

<td><%= short_date(document.created_at) %></td>

app/views/shared/documents/_term_footer.html.erb
<div class="float-right">
  <p style="margin-top: 50px; margin-bottom: 50px;">
    Guarapuava, <%= created_at %>.
  </p>
</div>

app/views/shared/documents/_term_header.html.erb
<div class="row mb-6">
  <div class="col-md-4 col-sm-4">
    <%= image_tag asset_path("utfpr_logo.png"), alt: "utfpr_logo", class: "img-fluid mb-2", style: "width: 350px;" %>
  </div>
  <div class="col-md-8 col-sm-8">
    <p class="m-0">Ministério da Educação</p>
    <p class="m-0">Universidade Tecnológica Federal do Paraná</p>
    <p class="m-0">Câmpus Guarapuava</p>
    <p class="m-0">Curso Superior de Tecnologia em Sistemas para Internet</p>
  </div>
</div>